rule download:
    input:
        "accession/AE014075.1"
    output:
        "data/{accession}.gbk",
        "data/{accession}.fasta",
    script:
        "script/download_genbank.py"


rule hmmscan:
    input:
        "data/Pfam-A_small.hmm",
        "data/{accession}_amino.fasta"
    output:
        "result/{accession}_domtblout.txt"
    script:
        "script/hmmscan.py"
